version: '3'
services:
  master:
    container_name: master
    hostname: master
    ports:
     - "8089:8089"
     - "5557:5557"
     - "5558:5558"
    image: "grubykarol/locust:0.13.5-python3.8-alpine3.11"
    environment:
      ATTACKED_HOST: http://master:8089
      LOCUST_MODE: master
      LOCUST_MASTER_BIND_PORT: 5557
      TASK_DELAY: 1000
      QUIET_MODE: "${QUIET_MODE:-false}"
    volumes:
      - ./locust-scripts:/locust

  slave:
    image: "grubykarol/locust:0.13.5-python3.8-alpine3.11"
    environment:
      ATTACKED_HOST: http://master:8089
      LOCUST_MODE: slave
      LOCUST_MASTER: master
      LOCUST_MASTER_BIND_PORT: 5557
      NO_PROXY: master
      TASK_DELAY: 1000
      QUIET_MODE: "${QUIET_MODE:-false}"
    volumes:
      - ./locust-scripts:/locust

