version: '3'
services:
  master:
    container_name: master
    hostname: master
    image: "grubykarol/locust:0.9.0-python3.6-alpine3.9"
    environment:
      ATTACKED_HOST: http://example.com
      LOCUST_MODE: master
      LOCUST_MASTER_BIND_PORT: 5557
      TASK_DELAY: 100
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--no-web --expect-slaves 1 -c 1 -r 1 -t 10s"
    volumes:
      - ./locust-scripts:/locust

  slave:
    image: "grubykarol/locust:0.9.0-python3.6-alpine3.9"
    environment:
      ATTACKED_HOST: http://example.com
      LOCUST_MODE: slave
      LOCUST_MASTER: master
      LOCUST_MASTER_BIND_PORT: 5557
      NO_PROXY: master
      TASK_DELAY: 100
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--no-web"
    volumes:
      - ./locust-scripts:/locust
